language:
  python
python:
  - 3.7
  - 3.8
  - 3.9

matrix:
  include:
    - os: linux
      dist: focal
      compiler: clang
      python: 3.7
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
          packages:
            - g++-10
            - uuid-dev
            - clang-10
    - os: linux
      dist: focal
      compiler: clang
      python: 3.8
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
          packages:
            - g++-10
            - uuid-dev
            - clang-10
    - os: linux
      dist: focal
      compiler: clang
      python: 3.9
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
          packages:
            - g++-10
            - uuid-dev
            - clang-10
    - os: osx
      compiler: clang
      osx_image: xcode10.2
    - os: linux
      dist: xenial
      compiler: clang
      python: 3.7
    - os: linux
      dist: xenial
      compiler: clang
      python: 3.8
    - os: linux
      dist: xenial
      compiler: clang
      python: 3.9
    - os: osx
      osx_image: xcode10.2
#    - os: linux
#      dist: trusty

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install ".[dev]" . # install package + test dependencies
script:
  - pytest
  - python examples/examples.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
