language:
  python

matrix:
  include:
    - os: linux
      dist: focal
      python: 3.7
    - os: linux
      dist: focal
      python: 3.8
    - os: linux
      dist: focal
      python: 3.9
    - os: linux
      dist: bionic
      python: 3.7
    - os: linux
      dist: bionic
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.9
    - os: osx
      # Would be nice to try different python versions :(
      #python: 3.7
      osx_image: xcode10.2

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install ".[test]" . # install package + test dependencies
script:
  - pytest
  - python examples/examples.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
