language:
  python
python:
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install ".[dev]" . # install package + test dependencies
jobs:
  include:
    - stage: Unit test
      script: pytest
    - stage: Integration test
      script: python examples/examples.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
