name: Python linting (black, isort, flake8, etc.)

on: [pull_request]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout
      - uses: ricardochaves/python-lint@v1.3.0
